FROM almalinux:9


# here we are telling our base image is almalinux:9





# docker file is starts from here 
# syntax starts from FROM IMAGE NAME
# IMAGE NAME is mandatory (base image is important for container we cannot creat new os from scratch we have to use it what we have )
