FROM spandanaerukulla/run:v1 
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

# EXPOSE is used to expose ports from our container
# here we are exposing port 80 from our container
# from our base image spandanaerukulla/run:v1 by giving spandanaerukulla/run:v1 we are telling if we dont have local image it will pull from docker hubS