FROM almalinux:9
LABEL  COURSE ="DOCKER" \
       AUTHOR="SPANDANA" \
       DURATION ="3HRS" \
       com.spandana.spandanafile.author= "spandanaerukulla@.com"
       

# LABEL is used to add metadata to our image
# Here we are adding course name , author name , duration and email id as metadata to our image
# lables are used for filteration and identification purpose