FROM almalinux:9
# CMD ["ping", "google.com"] we can over ride this CMD
ENTRYPOINT ["ping" , "google.com"] 

# ENTRYPOINT is used to set default application to be run when container starts
# here we are telling to run ping command when container starts