FROM run:v1
CMD ["nginx","-g", "daemon off;"]

# CMD is used to run commands when container starts
# here we are telling to run nginx in foreground when container starts
# nginx -g daemon off; is used to run nginx in foreground
# -g is used to the configuration directories
# daemon off; is used to run nginx  continously 