FROM almalinux:9   
RUN dnf install nginx -y # here we are installing nginx in our base image almalinux:9

# FROM is used to tell our base image
# almalinux:9 is our base image
# here we are installing nginx in our base image almalinux:9

# run command is used to install packages and to run commands in our base image
# here we are installing nginx package in our base image almalinux:9 using run command