FROM almalinux:9
ENV NAME="SPANDANA" \
    COURSE="DOCKER" \
    DURATION="3HRS" 
CMD ["sleep", "1000"]
    
## Here we are using ENV to set environment variables in our image
# if we want to set multiple environment variables we can use \ to continue in next line